socialbook/config/routes.rb
Rails.application.routes.draw do

  
  get 'welcome/index'  

  devise_for :users, 
           :path => '', 
           :path_names => { :sign_in => 'sign_in', 
                            :sign_up => 'sign_up', 
                            :sign_out => 'sign_out', 
                            :password => 'secret', 
                            :confirmation => 'verification' },
           :controllers => { :registrations => "my_devise" }

 resources :users

 resources :messages do 
   member do
     put "like", to: "messages#upvote"
     put "dislike", to: "messages#downvote"
     get "votes", to: "messages#votes"
   end
end

resources :users do 
   member do
     get "friendships", to: "users#friendships" 
     delete "remove_friend", to: "users#remove_friend" 
     put "friend_request", to: "users#friend_request" 
     put "accept_request", to: "users#accept_request"
     put "decline_request", to: "users#decline_request"
     get "manage", to: "users#manage"  
   end
end

 root 'welcome#index'

end

socialbook/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  acts_as_votable
  mount_uploader :image, ImageUploader
end

socialbook/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    if params[:id] == current_user.id.to_s
       @messages = current_user.messages
    else
       @messages = Message.where(user_id: [params[:id]]) 
    end
  end

  # GET /messages/new
  def new
    if current_user
      @message = Message.new
    else
      redirect_to new_user_session_path, :alert => "You have to sign in in order to post a message!"
    end
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user 
	@message.state = params[:option]
    respond_to do |format|
      if @message.save
        format.html { redirect_to new_message_path, notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { redirect_to new_message_path, alert: 'Message was not created succesfully' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
	  @message.state = params[:option]
      if @message.update(message_params)
        if current_user.has_role? :admin
          format.html { redirect_to message_path(:id => @message.user_id), notice: 'Message was successfully updated.' }
          format.json { render :show, status: :ok, location: @message }
        else
          format.html { redirect_to message_path(:id => current_user.id), notice: 'Message was successfully updated.' }
          format.json { render :show, status: :ok, location: @message }
        end
      else
        format.html { redirect_to edit_message_path, alert: 'Message was not updated succesfully' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    
    respond_to do |format|
      if current_user.has_role? :admin
		if @message.destroy
        	format.html { redirect_to message_path(:id => @message.user_id), notice: 'Message was successfully destroyed.' }
        	format.json { head :no_content }
		else
			format.html { redirect_to message_path(:id => @message.user_id), alert: 'Message was not destroyed succesfully' }
        	format.json { head :no_content }
		end
      else
		if @message.destroy
       		format.html { redirect_to message_path(:id => current_user.id), notice: 'Message was successfully destroyed.' }
        	format.json { head :no_content }
		else
			format.html { redirect_to message_path(:id => current_user.id), alert: 'Message was not destroyed succesfully' }
        	format.json { head :no_content }
		end
      end
    end
  end

  def upvote 
    @message = Message.find(params[:id])
    if @message.upvote_by current_user
		flash[:notice] = "Message was successfuly upvoted"
	else
		flash[:alert] = "Message was not succesfully upvoted"
	end
    redirect_to :back
  end  

  def downvote
    @message = Message.find(params[:id])
    if @message.downvote_by current_user
	flash[:notice] = "Message was successfuly downvoted"
	else
		flash[:alert] = "Message was not succesfully downvoted"
	end
    redirect_to :back
  end

  def votes
    @messages = current_user.find_voted_items
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
        params.require(:message).permit(:text, :user_id, :image, :remove_image)
    end
end

socialbook/app/helpers/messages_helper.rb
module MessagesHelper
end

socialbook/app/views/messages/_formEdit.html.erb
<div id="facebook-Bar">
  <div id="facebook-Frame">
<div id="logo"> <a href="">Socialbook</a> </div>  
</div> 
</div> 

<%= button_to "Go back", message_path(:id => current_user.id), :method => :get, :class => 'btn fbbutton', style: "margin-left:860px" %></br>


<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  &nbsp<%= f.label :"Edit your message:", style: "color: black;" %>    
    <div class="form-group">
   
    </br>&nbsp&nbsp<%= f.text_area(:text, size: '100x5', :autofocus => true, class: 'text_area') %>
  </div>

    
  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div> -->
 
  </br>

  <div class="field"></br>
    <%= f.label :"upload image:" %><br>
    </br><%= f.file_field :image %></br>
  </div> 

  <% if f.object.image? %>
      </br>Remove current image
      <%= f.check_box :remove_image %> 
  <% end %>
  
  </br>

  <div class="container">
    <label class='checkbox-inline'>
  <%= radio_button_tag :option, :private %>
  Private
</label>
<label class='checkbox-inline'>
  <%= radio_button_tag :option, :friends %>
  Share with friends
</label>
<label class='checkbox-inline'>
  <%= radio_button_tag :option, :public, checked = true %>
  Public
</label>
</div>

  </br>
  
</br
  <div class="actions">
    <%= f.submit "Edit", :class => 'fbbutton' %>
  </div>


<% end %>

socialbook/app/views/messages/_formPost.html.erb
<div id="facebook-Bar">
  <div id="facebook-Frame">
<div id="logo"> <a href="">Socialbook</a> </div>  
</div>
</div>

</br>

<%= button_to "Go to profile", user_path(:id => current_user.id), :method => :get, :class => 'btn fbbutton', style: "margin-left:860px" %></br>

<% flash.each do |name, msg| %>			
        <div class="<%= flash_class(name) %>">		
  		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  		<strong><%= content_tag :div, msg, :id => "flash_#{name}" %></strong>
	</div>
<% end %>

<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  &nbsp<%= f.label :"Write your message:", style: "color: black;" %>    
    <div class="form-group">
   
    </br>&nbsp&nbsp<%= f.text_area(:text, size: '100x5', :autofocus => true, class: 'text_area') %>
  </div>

    
  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div> -->

  <div class="field"></br>
    <%= f.label :"upload image:" %><br>
    </br><%= f.file_field :image %></br>
  </div>  

  </br>

  <div class="container">
    <label class='checkbox-inline'>
  <%= radio_button_tag :option, :private %>
  Private
</label>
<label class='checkbox-inline'>
  <%= radio_button_tag :option, :friends %>
  Share with friends
</label>
<label class='checkbox-inline'>
  <%= radio_button_tag :option, :public, checked = true %>
  Public
</label>
</div>

  </br>

</br
  <div class="actions">
    <%= f.submit "Post", :class => 'fbbutton' %>
  </div>


<% end %>

socialbook/app/views/messages/edit.html.erb
<%= render 'formEdit', message: @message %>

socialbook/app/views/messages/new.html.erb
<%= render 'formPost', message: @message %>

socialbook/app/views/messages/show.html.erb
<div id="facebook-Bar">
  <div id="facebook-Frame"> 
<div id="logo"> <a href="">Socialbook</a> </div> 
</div> 
</div> 


<!DOCTYPE html>
<html>
<head>
<style>
* {
  box-sizing: border-box;
}
</style>
</head>
<body>

</br>

<% if current_user.has_role? :admin %>
  <%= button_to "Go back", manage_user_path(:id => current_user.id), :method => :get, :class => 'btn fbbutton', style: "margin-left:860px" %></br>
<% else %>
  <%= button_to "Go to profile", user_path(:id => current_user.id), :method => :get, :class => 'btn fbbutton', style: "margin-left:860px" %></br>
<% end %>

<% flash.each do |name, msg| %>			
        <div class="<%= flash_class(name) %>">		
  		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  		<strong><%= content_tag :div, msg, :id => "flash_#{name}" %></strong>
	</div>
<% end %>

</br>

<input type="text" id="myInput" onkeyup="filter()" placeholder="Search for messages.." title="Type in a text">

<h2>Messages</h2></br>

<table id="myTable">
  <tr class="header">
    <th style="width:25%;">Text</th>
    <th style="width:25%;">Photo</th>
    <th style="width:25%;">State</th>
    <th style="width:5%;">Likes</th>
    <th style="width:10%;">Dislikes</th>
    <th style="width:5%;"></th>
    <th style="width:10%;"></th>
  </tr>
<% @messages.each do |msg| %>
  <tr>
	<% if (msg.user_id == current_user.id) || (current_user.has_role? :admin) %>   
    	<td><%= msg.text %></td>
    	<td><%= image_tag msg.image.thumb.url if msg.image? %></td>
    	<td><%= msg.state %></td>
    	<td><%= msg.get_upvotes.size %></td>
    	<td><%= msg.get_downvotes.size %></td>
      	<td><%= button_to "Edit", edit_message_path(msg), :method => :get, :class => "btn fbbutton" %></td>
      	<td><%= button_to "Delete", msg, :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'btn fbbutton' %></td> 
	<% else %>
    	<% if (msg.state == 'public') || ((msg.state == 'friends') && (current_user.friends_with?(User.find(msg.user_id)))) %>
			<td><%= msg.text %></td>
    		<td><%= image_tag msg.image.thumb.url if msg.image? %></td>
    		<td><%= msg.state %></td>
    		<td><%= msg.get_upvotes.size %></td>
    		<td><%= msg.get_downvotes.size %></td>
      		<td><%= button_to "Like", like_message_path(msg), :method => :put, :class => "btn fbbutton" %></td>
      		<td><%= button_to "Dislike", dislike_message_path(msg), :method => :put, :class => "btn fbbutton" %></td>
    	<% end %>
  	<% end %>

  </tr>
 <% end %>
</table>


<script>
function filter() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>

socialbook/app/views/messages/votes.html.erb
<div id="facebook-Bar">
  <div id="facebook-Frame"> 
<div id="logo"> <a href="">Socialbook</a> </div> 
</div> 
</div> 

<!DOCTYPE html>
<html>
<head>
<style>
* {
  box-sizing: border-box;
}

</style>
</head>
<body>

</br>

<%= button_to "Go to profile", user_path(:id => current_user.id), :method => :get, :class => 'btn fbbutton', style: "margin-left:860px" %></br>

<input type="text" id="myInput" onkeyup="filter()" placeholder="Search for messages.." title="Type in a text">

<h2>My votes</h2></br>

<table id="myTable">
  <tr class="header">    
    <th style="width:25%;">Text</th>
    <th style="width:25%;">Photo</th>
    <th style="width:25%;">User</th>    
    <th style="width:25%;">Vote</th>
  </tr>
<% @messages.each do |msg| %>
  <tr>
    <% if (msg.state == 'public') || ((msg.state == 'friends') && (current_user.friends_with?(User.find(msg.user_id)))) %>
    	<td><%= msg.text %></td>
    	<td><%= image_tag msg.image.thumb.url if msg.image? %></td>
    	<td><%= User.find(msg.user_id).name %></td>
    	<% if current_user.voted_up_on? msg %>
      		<td>Like</td>
    	<% else %>
      		<td>Dislike</td>
  </tr>
 		<% end %>
	<% end %>
<% end %>
</table>


<script>
function filter() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>