socialbook/config/routes.rb
Rails.application.routes.draw do

  
  get 'welcome/index'  

  devise_for :users, 
           :path => '', 
           :path_names => { :sign_in => 'sign_in', 
                            :sign_up => 'sign_up', 
                            :sign_out => 'sign_out', 
                            :password => 'secret', 
                            :confirmation => 'verification' },
           :controllers => { :registrations => "my_devise" }

 resources :users

 resources :messages do 
   member do
     put "like", to: "messages#upvote"
     put "dislike", to: "messages#downvote"
     get "votes", to: "messages#votes"
   end
end

resources :users do 
   member do
     get "friendships", to: "users#friendships" 
     delete "remove_friend", to: "users#remove_friend" 
     put "friend_request", to: "users#friend_request" 
     put "accept_request", to: "users#accept_request"
     put "decline_request", to: "users#decline_request"
     get "manage", to: "users#manage"  
   end
end

 root 'welcome#index'

end

socialbook/app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :messages
  acts_as_voter
  has_friendship
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def update_without_password(params, *options)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

socialbook/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
	dontShow = []
	dontShow.push(current_user.id)
	(User.all).each { |u| if u.has_role? :admin then dontShow.push(u) end }
	
    @users = User.where.not(id: dontShow) 
  end

  def show
    Socialbook::Application.config.id = current_user.id
  end

  def edit
	if current_user.has_role? :admin
	  Socialbook::Application.config.id = current_user.id
    end
    @user = User.find(params[:id])
    sign_in(@user)    
    redirect_to edit_user_registration_path
  end

  def friendships
    @u = User.find(params[:id])
    @friends = User.find(params[:id]).friends
    @requested = User.find(params[:id]).requested_friends 
    @pending = User.find(params[:id]).pending_friends    
  end

  def remove_friend
    ids = params[:id].split(",")
    if User.find(ids[0]).remove_friend(User.find(ids[1]))
		flash[:notice] = "Friend was successfully removed"
	else
		flash[:alert] = "Friend was not succesfully removed"
	end
    redirect_to :back
  end

  def friend_request
    if current_user.friend_request(User.find(params[:id]))
		flash[:notice] = "Request was successfully sent"
	else
		flash[:alert] = "Request was not succesfully sent"
	end
    redirect_to :back
  end

  def accept_request
    ids = params[:id].split(",")
    if User.find(ids[0]).accept_request(User.find(ids[1]))
		flash[:notice] = "Request was successfully accepted"
	else
		flash[:alert] = "Request was not succesfully accepted"
	end
    redirect_to :back
  end

  def decline_request
    ids = params[:id].split(",")
    if User.find(ids[0]).decline_request(User.find(ids[1]))
		flash[:notice] = "Request was successfully declined"
	else
		flash[:alert] = "Request was not succesfully declined"
	end
    redirect_to :back
  end

  def manage
	if current_user.has_role? :admin
	  Socialbook::Application.config.id = current_user.id
    end
	sign_in(User.find(Socialbook::Application.config.id))  
    @users = User.where.not(id: [Socialbook::Application.config.id])       
  end



end

socialbook/app/helpers/user_helper.rb
module UserHelper
end

socialbook/app/views/users/friendships.html.erb
<div id="facebook-Bar">
  <div id="facebook-Frame"> 
<div id="logo"> <a href="">Socialbook</a> </div> 
</div> 
</div> 


<!DOCTYPE html>
<html>
<head>
<style>
* {
  box-sizing: border-box;
}
</style>
</head>
<body>

</br>

<% if current_user.has_role? :admin %>
  <%= button_to "Go back", manage_user_path(:id => current_user.id), :method => :get, :class => 'btn fbbutton', style: "margin-left:860px" %></br>
<% else %>
  <%= button_to "Go to profile", user_path(:id => current_user.id), :method => :get, :class => 'btn fbbutton', style: "margin-left:860px" %></br>
<% end %>

<% flash.each do |name, msg| %>			
        <div class="<%= flash_class(name) %>">		
  		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  		<strong><%= content_tag :div, msg, :id => "flash_#{name}" %></strong>
	</div>
<% end %>

</br>

<% if current_user.has_role? :admin %>
	<h2>Friends</h2></br>
<% else %>
	<h2>My Friends</h2></br>
<% end %>

<input type="text" id="friendsInput" onkeyup="friendsFilter()" placeholder="Search for friends.." title="Type in a text" class="myInput">

<table id="friends" class="myTable">
  <tr class="header">
    <th style="width:25%;">User</th>
    <th style="width:25%;"></th>
    <th style="width:25%;"></th>
  </tr>
<% @friends.each do |f| %>
  <tr>
    <td><%= f.name %></td>
    <td><%= button_to "messages", message_path(:id => f.id), :method => :get, :class => "btn fbbutton" %></td>
    <td><%= button_to "remove", remove_friend_user_path(:id => @u.id.to_s+','+f.id.to_s), :method => :delete, :class => "btn fbbutton" %></td>
  </tr>
<% end %>
</table>

</br>
</br>

<h2>Requested</h2></br>

<input type="text" id="requestedInput" onkeyup="requestedFilter()" placeholder="Search for requested friendships.." title="Type in a text" class="myInput">

<table id="requested" class="myTable">
  <tr class="header">
    <th style="width:25%;">User</th>
    <th style="width:25%;"></th>
    <th style="width:25%;"></th>
  </tr>
<% @requested.each do |r| %>
  <tr>
    <td><%= r.name %></td>
    <td><%= button_to "accept", accept_request_user_path(:id => @u.id.to_s+','+r.id.to_s), :method => :put, :class => "btn fbbutton" %></td>
    <td><%= button_to "decline", decline_request_user_path(:id => @u.id.to_s+','+r.id.to_s), :method => :put, :class => "btn fbbutton" %></td>
  </tr>
<% end %>
</table>

</br>
</br>

<h2>Pending</h2></br>

<input type="text" id="pendingInput" onkeyup="pendingFilter()" placeholder="Search for pending requests.." title="Type in a text" class="myInput">

<table id="pending" class="myTable">
  <tr class="header">
    <th style="width:25%;">User</th>
  </tr>
<% @pending.each do |p| %>
  <tr>
    <td><%= p.name %></td>    
  </tr>
<% end %>
</table>


<script>
function friendsFilter() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("friendsInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("friends");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}

function requestedFilter() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("requestedInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("requested");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}

function pendingFilter() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("pendingInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("pending");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>

socialbook/app/views/users/index.html.erb
<div id="facebook-Bar">
  <div id="facebook-Frame"> 
<div id="logo"> <a href="">Socialbook</a> </div> 
</div> 
</div> 


<!DOCTYPE html>
<html>
<head>
<style>
* {
  box-sizing: border-box;
}
</style>
</head>
<body>

</br>

<%= button_to "Go to profile", user_path(:id => current_user.id), :method => :get, :class => 'btn fbbutton', style: "margin-left:860px" %></br>

<% flash.each do |name, msg| %>			
        <div class="<%= flash_class(name) %>">		
  		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  		<strong><%= content_tag :div, msg, :id => "flash_#{name}" %></strong>
	</div>
<% end %>

</br>

<input type="text" id="myInput" onkeyup="filter()" placeholder="Search for users.." title="Type in a text">

<h2>Users</h2></br>

<table id="myTable">
  <tr class="header">
    <th style="width:20%;">Name</th>
    <th style="width:20%;"></th>
    <th style="width:20%;"></th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= button_to "messages", message_path(:id => user.id), :method => :get, :class => "btn fbbutton" %></td>
    <td><%= button_to "send request", friend_request_user_path(:id => user.id), :method => :put, :class => "btn fbbutton" %></td>
  </tr>
  <% end %>
</table>


<script>
function filter() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>

socialbook/app/views/users/manage.html.erb
<div id="facebook-Bar">
  <div id="facebook-Frame"> 
<div id="logo"> <a href="">Socialbook</a> </div> 
</div> 
</div> 


<!DOCTYPE html>
<html>
<head>
<style>
* {
  box-sizing: border-box;
}
</style>
</head>
<body>

</br>

<% flash.each do |name, msg| %>			
        <div class="<%= flash_class(name) %>">		
  		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  		<strong><%= content_tag :div, msg, :id => "flash_#{name}" %></strong>
	</div>
<% end %>

</br>

<%= button_to "Edit profile", edit_user_registration_path(:user => current_user), :method => :get, :class => 'btn fbbutton', style: "margin-left:860px" %></br>
<%= button_to "Sign out", destroy_user_session_path(), :method => :delete, :class => 'btn fbbutton', style: "margin-left:860px" %></br>

<input type="text" id="myInput" onkeyup="filter()" placeholder="Search for users.." title="Type in a text">

<h2>Users</h2></br>

<table id="myTable">
  <tr class="header">
    <th style="width:25%;">Id</th>
    <th style="width:25%;">Name</th>
    <th style="width:25%;">Email</th>
    <th style="width:25%;">Role</th>
    <th style="width:5%;"></th>
    <th style="width:10%;"></th>
    <th style="width:5%;"></th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <% if user.has_role? :admin %>
	<td>admin</td>
	<% else %>
	<td>default</td>
	<% end %>
    <td><%= button_to "Edit", edit_user_path(:id => user.id), :method => :get, :class => "btn fbbutton" %></td>
    <td><%= button_to "Messages", message_path(:id => user.id), :method => :get, :class => "btn fbbutton" %></td> 
    <td><%= button_to "Friendships", friendships_user_path(:id => user.id), :method => :get, :class => "btn fbbutton" %></td>
  </tr>
  <% end %>
</table>


<script>
function filter() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>

socialbook/app/views/users/show.html.erb
 <!DOCTYPE html>
<html lang="en">
<head>
  <title>Socialbook</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="application.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>


<!-- header starts here -->
  


  <form>
    
<div id="facebook-Bar">
  <div id="facebook-Frame">
<div id="logo"> <a href="">Socialbook</a> </div>  
 

      </div>
</div>
      </div>
</form>


<div class="container-buttons">


<% flash.each do |name, msg| %>		
        </br>	
        <div class="<%= flash_class(name) %>">		
  		<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  		<strong><%= content_tag :div, msg, :id => "flash_#{name}" %></strong>		
	</div>
</br>
<% end %>

<%= link_to(' Edit profile', edit_user_registration_path, :class => 'btn btn-default glyphicon glyphicon-list-alt',:method=>:get) %>
<%= link_to(' Post message', new_message_path(), :class => 'btn btn-default glyphicon glyphicon-list-alt',:method=>:get) %>
<%= link_to(' My messages', message_path(:id => current_user.id), :class => 'btn btn-default glyphicon glyphicon-envelope',:method=>:get) %>
<%= link_to(' Search users', users_path(), :class => 'btn btn-default glyphicon glyphicon-search',:method=>:get) %>
<%= link_to(' My friendhips', friendships_user_path(current_user.id), :class => 'btn btn-default glyphicon glyphicon-user',:method=>:get) %>
<%= link_to(' My votes', votes_message_path(current_user.id), :class => 'btn btn-default glyphicon glyphicon-thumbs-up',:method=>:get) %>
<%= link_to(' Sign out', destroy_user_session_path, :class => 'btn btn-default glyphicon glyphicon-log-out',:method=>:delete) %>

</div>

</br>

<div class="row">
      <div class="col-sm-2"> <div class="panel-group">
    <div class="panel panel-default-custom">
      <div class="panel-heading">Name</div>
      <div class="panel-body"><%= current_user.name %></div>
      <div class="panel-heading">Email</div>
      <div class="panel-body"><%= current_user.email %></div>
      <div class="panel-heading">Messages</div>
      <div class="panel-body"><%= current_user.messages.count %></div>
	
	
    </div>
	
   
  </div>
</div>

<div class="col-sm-8"></div>

      <div class="col-sm-2"> <div class="panel-group">
    <div class="panel panel-default-custom">
	  <div class="panel-heading">Friends</div>
      <div class="panel-body"><%= current_user.friends.count %></div>
	  <div class="panel-heading">Received requests</div>
      <div class="panel-body"><%= current_user.requested_friends.count %></div>
	  <div class="panel-heading">My requests</div>
      <div class="panel-body"><%= current_user.pending_friends.count %></div>

	
	
    </div>
	
   
  </div>
</div>
    </div>
 





 	
      	